# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$directory$git_branch$git_status$cmd_duration
$character"""

[cmd_duration]
min_time = 100
show_milliseconds = true
format = "[$duration]($style) "
style = "bold yellow"
disabled = false

# Replace the '>' symbol in the prompt with '->'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[>](purple)' # The 'success_symbol' segment is being set
error_symbol = '[>](red)'
